// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BlazorAPI.Models;

public partial class BlazorAPIBancodbContext : DbContext
{
    public BlazorAPIBancodbContext(DbContextOptions<BlazorAPIBancodbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TbTarefa> TbTarefas { get; set; }

    public virtual DbSet<TbUsuario> TbUsuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TbTarefa>(entity =>
        {
            entity.HasKey(e => e.IdTarefa);

            entity.ToTable("tb_tarefa");

            entity.Property(e => e.IdTarefa).HasColumnName("id_tarefa");
            entity.Property(e => e.FkUsuario).HasColumnName("fk_usuario");
            entity.Property(e => e.TaData)
                .IsRequired()
                .HasColumnName("ta_data");
            entity.Property(e => e.TaDescricao)
                .IsRequired()
                .HasColumnName("ta_descricao");
            entity.Property(e => e.TaPrazo).HasColumnName("ta_prazo");
            entity.Property(e => e.TaPrioridade)
                .IsRequired()
                .HasColumnName("ta_prioridade");
            entity.Property(e => e.TaStatus)
                .IsRequired()
                .HasColumnName("ta_status");
            entity.Property(e => e.TaTitulo)
                .IsRequired()
                .HasColumnName("ta_titulo");

            entity.HasOne(d => d.FkUsuarioNavigation).WithMany(p => p.TbTarefas)
                .HasForeignKey(d => d.FkUsuario)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TbUsuario>(entity =>
        {
            entity.HasKey(e => e.IdUsuario);

            entity.ToTable("tb_usuario");

            entity.Property(e => e.IdUsuario).HasColumnName("id_usuario");
            entity.Property(e => e.UsLogin)
                .IsRequired()
                .HasColumnName("us_login");
            entity.Property(e => e.UsNome)
                .IsRequired()
                .HasColumnName("us_nome");
            entity.Property(e => e.UsSenha)
                .IsRequired()
                .HasColumnName("us_senha");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}