// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace BlazorAPI.Models;

public partial class TbTarefa
{
    [Key]
    [Column("id_tarefa")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdTarefa { get; set; }

    [Column("ta_titulo")]
    public string TaTitulo { get; set; }

    [Column("ta_descricao")]
    public string TaDescricao { get; set; }

    [Column("ta_prioridade")]
    public string TaPrioridade { get; set; }

    [Column("ta_prazo")]
    public int TaPrazo { get; set; }

    [Column("ta_status")]
    public string TaStatus { get; set; }

    [Column("ta_data")]
    public string TaData { get; set; }

    [Column("fk_usuario")]
    public int FkUsuario { get; set; }

    [ForeignKey("FkUsuario")]
    public virtual TbUsuario FkUsuarioNavigation { get; set; }
}