// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using BlazorAPI.DTOs.Tarefa;

namespace BlazorAPI.Models;

public partial class TbTarefa
{
    [Key]
    [Column("id_tarefa")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdTarefa { get; set; }

    [Column("ta_titulo")]
    public string TaTitulo { get; set; }

    [Column("ta_descricao")]
    public string TaDescricao { get; set; }

    [Column("ta_prioridade")]
    public string TaPrioridade { get; set; }

    [Column("ta_prazo")]
    public int TaPrazo { get; set; }

    [Column("ta_status")]
    public string TaStatus { get; set; }

    [Column("ta_data")]
    public string TaData { get; set; }

    [Column("fk_usuario")]
    public int FkUsuario { get; set; }

    [ForeignKey("FkUsuario")]
    public virtual TbUsuario FkUsuarioNavigation { get; set; }

    public static implicit operator TbTarefa(TarefaDTO _dadosTarefaCadastro) =>
            new()
            {
                IdTarefa = _dadosTarefaCadastro.Id,
                TaTitulo = _dadosTarefaCadastro.Titulo,
                TaDescricao = _dadosTarefaCadastro.Descricao,
                TaPrioridade = _dadosTarefaCadastro.Prioridade,
                TaPrazo = _dadosTarefaCadastro.Prazo,
                TaStatus = _dadosTarefaCadastro.Status,
                TaData = DateTime.Now.ToString(),
            };


    public static implicit operator TarefaDTO(TbTarefa _tarefa) =>
    new()
    {
        Id = _tarefa.IdTarefa,
        Titulo = _tarefa.TaTitulo,
        Descricao = _tarefa.TaDescricao,
        Prioridade = _tarefa.TaPrioridade,
        Prazo = _tarefa.TaPrazo,
        Status = _tarefa.TaStatus
    };


    public static implicit operator TarefaConsultaDTO(TbTarefa _tarefa) =>
 new()
 {
     Id = _tarefa.IdTarefa,
     Titulo = _tarefa.TaTitulo,
     Descricao = _tarefa.TaDescricao,
     Prioridade = _tarefa.TaPrioridade,
     Prazo = _tarefa.TaPrazo,
     Status = _tarefa.TaStatus
 };
}