// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorAPI.Models;

public partial class TbUsuario
{
    [Key]
    [Column("id_usuario")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdUsuario { get; set; }

    [Column("us_nome")]
    public string UsNome { get; set; }

    [Column("us_login")]
    public string UsLogin { get; set; }

    [Column("us_senha")]
    public string UsSenha { get; set; }

    public virtual ICollection<TbTarefa> TbTarefas { get; set; } = new List<TbTarefa>();
}